# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=30)),
                ('environment_id', models.PositiveSmallIntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, b'Pass'), (0, b'Fail'), (2, b'In Progress')], default=2)),
                ('log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
